packages:
  - name: card
    actions:
      - name: read
        runtime: 'go:default'
      - name: new
        runtime: 'go:default'
      - name: update
        runtime: 'go:default'
      - name: delete
        runtime: 'go:default'
      - name: test
        runtime: 'nodejs:default'
  # - name: OTP # todo
