packages:
	- name: card
	actions:
	- name: create
		runtime: 'nodejs:18'
	- name: read
		runtime: 'nodejs:18'
	- name: update
		runtime: 'nodejs:18'
	- name: delete
		runtime: 'nodejs:18'
	# - name: OTP # todo
